apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wp
  namespace: app
spec:
  releaseName: wp
  chart:
    spec:
      chart: wordpress
      sourceRef:
        kind: HelmRepository
        name: wp
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: wp-values
