# add this part to dev and prod instead let it here
# ingress
ingress:
  enabled: true
  hostname: wp.benighil-mohamed.com
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  extraTls:
  - hosts: 
      - "{{ .Values.ingress.hostname }}" 
    secretName: "{{ .Release.Name }}-{{ .Values.ingress.hostname }}"