apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wp
  namespace: app


# add this part to dev and prod instead let it here
# ingress
spec:
  values:
    ingress:
      enabled: true
      hostname: app.benighil-mohamed.com
      path: /
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      extraTls:
      - hosts: 
          - "{{ .Values.ingress.hostname }}" 
        secretName: "{{ .Release.Name }}-{{ .Values.ingress.hostname }}"